### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Olekmi** [akb89/word2vec#12]
Exception has occurred: ModuleNotFoundError
No module named 'logging.config'
  File "C:\Users\Olek\word2vec-master\word2vec\main.py", line 10, in <module>
    import logging.config

**Comment by akb89** [comment]
How did you install the module? What is your python version?

**Comment by Olekmi** [comment]
Via console setup file and I used python 3.6-------- Message original --------De : akb89 <notifications@github.com>Date : dim. 5 avr. 2020 à 19:17À : akb89/word2vec <word2vec@noreply.github.com>Cc : Olekmi <michonskialeksander@gmail.com>, Author <author@noreply.github.com>Objet : Re: [akb89/word2vec] ModuleNotFoundError (#12)
How did you install the module? What is your python version?

**Comment by akb89** [comment]
What happens when you type: "import logging" and "import logging.config" directly into your python3 interpreter?

**Comment by Olekmi** [comment]
Import logging adds the folder as a package, but I can't see the config
file in the folder. Is it a system file?

**Comment by akb89** [comment]
logging.config is a python package itself. The error message you get "No module named 'logging.config'" suggests that there is a problem with your python installation, not the word2vec module itself. 
Within a terminal, type 'python3' to enter the python3 interpreter, then type in 'import logging' and then 'import logging.config'. If you get the error message again this would confirm that the problem comes from your python installation

**Comment by Olekmi** [comment]
[image: image.png]
Like this?

**Comment by akb89** [comment]
I cannot see the image

**Comment by Olekmi** [comment]
![unnamed](https://user-images.githubusercontent.com/48719422/78535786-0864ce00-77ed-11ea-9710-349f0839a409.png)

**Comment by akb89** [comment]
The python version indicated here is 3.7, not 3.6 as you mentioned earlier: are you using the same python version to install the word2vec module? I would recommend using virtualenv to make a clean and separate installation

**Comment by Olekmi** [comment]
That is how I did it. I tried both versions.

**Comment by akb89** [comment]
Do you install via pip, setup.py install or setup.py develop?

**Comment by akb89** [comment]
And you get the error message in all python versions? But in none when using the interpreter and typing the command directly?

**Comment by Olekmi** [comment]
when I install via pip:
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.1 (from tf-word2vec) (from versions: 2.2.0rc1, 2.2.0rc2)
ERROR: No matching distribution found for tensorflow==2.0.1 (from tf-word2vec)

**Comment by akb89** [comment]
Ok, what you can do is install tensorflow separately:
- pip3 install tensorflow (should install the latest 2.x version available)
- python3 setup.py develop under the word2vec directory (after git clone) in order to install a development version of tf-word2vec

**Comment by Olekmi** [comment]
pip3 install tensorflow (should install the latest 2.x version available) - > I have the latest version 2.1.0 and still I get the same error when I install via pip

**Comment by akb89** [comment]
Install what via pip? Word2Vec? Don't install tf-word2vec via pip, do a git clone and then under the word2vec directory do `python3 setup.py develop`

**Comment by Olekmi** [comment]
![image](https://user-images.githubusercontent.com/48719422/78541432-e754ab00-77f5-11ea-819f-794feaf89391.png)
I did not receive any confirmation it has been installed.

**Comment by akb89** [comment]
Is setup.py under word2vec-master? Can you show me the output of `ls -l`?

**Comment by Olekmi** [comment]
Yes, it is.
'ls' is not recognized as an internal or external command,
operable program or batch file.

**Comment by akb89** [comment]
What about running `python3 setup.py install`?

**Comment by Olekmi** [comment]
The same result as with develop. No prompt.

**Comment by akb89** [comment]
Then I don't know: do you have access to a UNIX-based virtual machine? I can't debug windows stuff any further unfortunately

**Comment by Olekmi** [comment]
Yes, VMware linux.

**Comment by akb89** [comment]
Ok good, try it out on Ubuntu or Debian-based distrib and see how it goes. Should work on python 3.6 ad 3.7. If you get the same error when installing via pip, try out `python3 setup.py install` after a git clone and let me know

**Comment by Olekmi** [comment]
No, sorry, I can't log in. It is strange I can log in to the same VM for Win desktop, but not for linux.
How can I do the assignment?

**Comment by akb89** [comment]
Install Linux with VirtualBox (or VMWare) on your Windows: https://itsfoss.com/install-linux-in-virtualbox/
